### ISSUE TITLE
Attribute entity displayed as a number, but needle not working properly

### ISSUE THREAD

**Issue by Nikolay-Ch** [radimkeseg/lovelace-mini-gauge-card#3]
Ex, for configuration:
```yaml
- type: custom:mini-gauge-card
  entity: switch.socket.voltage
  title: Switch
  decimals: 2
  scale: 2
  severity:
    green: 200
    yellow: 180
    red: 0
  min: 150
  max: 300
```
![image](https://user-images.githubusercontent.com/24368057/154579944-79b7b289-f551-4b5e-8de3-364220186556.png)
