### ISSUE TITLE
Bar not working under Zero

### ISSUE THREAD

**Issue by Ringo982** [radimkeseg/lovelace-mini-gauge-card#4]
Hello
i'm trying to use this card to create a gauge from -6 to +6.
I have set red from -6, yellow from 0, green from 1.5
The problem is that when the value goes under zero, i do not see red, but yellow (it is not the real yellow bar, but it seems a layered yellow with the gray line behind).
It seems that your gauge bar is not working for values under zero.
Can you help please?
Thanks a lot

**Comment by radimkeseg** [comment]
![image](https://user-images.githubusercontent.com/25863962/218808331-62337f42-b8d9-42d7-a522-eb4c3b8e6f74.png)

```
type: custom:mini-gauge-card
entity: input_number.test_num
title: Test
decimals: 2
scale: 2
severity:
  green: 1.5
  yellow: 0
  red: -6
min: -20
max: 20

```
